import { Salon, Service, Staff, Review, ServiceCategory, Booking, StaffAvailability } from '@/types';

export const mockCategories: ServiceCategory[] = [
  { id: '1', name: 'Haircut', icon: 'scissors', created_at: new Date().toISOString() },
  { id: '2', name: 'Coloring', icon: 'palette', created_at: new Date().toISOString() },
  { id: '3', name: 'Styling', icon: 'sparkles', created_at: new Date().toISOString() },
  { id: '4', name: 'Spa & Massage', icon: 'spa', created_at: new Date().toISOString() },
  { id: '5', name: 'Nails', icon: 'hand', created_at: new Date().toISOString() },
  { id: '6', name: 'Makeup', icon: 'lipstick', created_at: new Date().toISOString() },
];

export const mockSalons: Salon[] = [
  {
    id: '1',
    owner_id: 'owner-1',
    name: 'Luxe Beauty Studio',
    slug: 'luxe-beauty-studio',
    description: 'A premier destination for luxury beauty treatments. Our expert stylists bring decades of experience to every appointment.',
    address: '123 Galle Road, Colombo 03',
    city: 'Colombo',
    latitude: 6.9271,
    longitude: 79.8612,
    phone: '+94 11 234 5678',
    email: 'hello@luxebeauty.lk',
    cover_image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
    logo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200',
    status: 'approved',
    rating: 4.9,
    review_count: 127,
    commission_rate: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    owner_id: 'owner-2',
    name: 'Serenity Spa & Salon',
    slug: 'serenity-spa-salon',
    description: 'Experience tranquility and transformation at our award-winning spa. We specialize in holistic beauty treatments.',
    address: '45 Temple Street, Kandy',
    city: 'Kandy',
    latitude: 7.2906,
    longitude: 80.6337,
    phone: '+94 81 234 5678',
    email: 'info@serenityspa.lk',
    cover_image: 'https://images.unsplash.com/photo-1600948836101-f9ffda59d250?w=800',
    logo: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=200',
    status: 'approved',
    rating: 4.7,
    review_count: 89,
    commission_rate: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    owner_id: 'owner-3',
    name: 'The Cutting Edge',
    slug: 'the-cutting-edge',
    description: 'Modern artistry meets classic technique. Our team of creative professionals redefine beauty standards.',
    address: '78 Church Street, Galle Fort',
    city: 'Galle',
    latitude: 6.0535,
    longitude: 80.2210,
    phone: '+94 91 234 5678',
    email: 'book@cuttingedge.lk',
    cover_image: 'https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=800',
    logo: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=200',
    status: 'approved',
    rating: 4.8,
    review_count: 156,
    commission_rate: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    owner_id: 'owner-4',
    name: 'Glow & Glamour',
    slug: 'glow-glamour',
    description: 'Where beauty dreams come true. Specializing in bridal and special occasion styling.',
    address: '23 Main Street, Negombo',
    city: 'Negombo',
    latitude: 7.2094,
    longitude: 79.8358,
    phone: '+94 31 234 5678',
    email: 'beauty@glowglamour.lk',
    cover_image: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800',
    logo: 'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=200',
    status: 'approved',
    rating: 4.6,
    review_count: 72,
    commission_rate: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    owner_id: 'owner-5',
    name: 'Mountain Bliss Wellness',
    slug: 'mountain-bliss-wellness',
    description: 'Escape to our hillside retreat for premium spa and wellness treatments with stunning views.',
    address: '12 Grand Hotel Road, Nuwara Eliya',
    city: 'Nuwara Eliya',
    latitude: 6.9497,
    longitude: 80.7891,
    phone: '+94 52 234 5678',
    email: 'relax@mountainbliss.lk',
    cover_image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
    logo: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=200',
    status: 'approved',
    rating: 4.8,
    review_count: 64,
    commission_rate: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockStaff: Staff[] = [
  {
    id: '1',
    salon_id: '1',
    user_id: null,
    name: 'Isabella Chen',
    title: 'Senior Stylist',
    bio: 'With 15 years of experience in high-fashion styling, Isabella brings artistry to every cut.',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    salon_id: '1',
    user_id: null,
    name: 'Marcus Rivera',
    title: 'Color Specialist',
    bio: 'Award-winning colorist known for creating stunning balayage and ombre effects.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    salon_id: '1',
    user_id: null,
    name: 'Sophia Martinez',
    title: 'Spa Therapist',
    bio: 'Certified massage therapist specializing in deep tissue and aromatherapy treatments.',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    salon_id: '1',
    category_id: '1',
    name: 'Signature Haircut',
    description: 'A personalized haircut experience including consultation, wash, cut, and style.',
    duration_minutes: 60,
    price: 85,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    salon_id: '1',
    category_id: '2',
    name: 'Full Color Treatment',
    description: 'Complete color transformation with premium products and expert application.',
    duration_minutes: 120,
    price: 180,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    salon_id: '1',
    category_id: '2',
    name: 'Balayage Highlights',
    description: 'Hand-painted highlights for a natural, sun-kissed look.',
    duration_minutes: 150,
    price: 250,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    salon_id: '1',
    category_id: '3',
    name: 'Blowout & Style',
    description: 'Professional blowout with heat styling for any occasion.',
    duration_minutes: 45,
    price: 65,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    salon_id: '1',
    category_id: '4',
    name: 'Luxury Spa Massage',
    description: '90-minute full body massage with aromatherapy oils.',
    duration_minutes: 90,
    price: 150,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    salon_id: '1',
    category_id: '5',
    name: 'Gel Manicure',
    description: 'Long-lasting gel polish with nail shaping and cuticle care.',
    duration_minutes: 45,
    price: 55,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    booking_id: 'booking-1',
    customer_id: 'customer-1',
    salon_id: '1',
    rating: 5,
    comment: 'Absolutely amazing experience! Isabella is incredibly talented and really listened to what I wanted.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    customer: {
      id: 'profile-1',
      user_id: 'customer-1',
      full_name: 'Emily Johnson',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
      phone: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '2',
    booking_id: 'booking-2',
    customer_id: 'customer-2',
    salon_id: '1',
    rating: 5,
    comment: 'Best salon in the city! The atmosphere is so luxurious and the results speak for themselves.',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    customer: {
      id: 'profile-2',
      user_id: 'customer-2',
      full_name: 'Michael Thompson',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
      phone: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: '3',
    booking_id: 'booking-3',
    customer_id: 'customer-3',
    salon_id: '1',
    rating: 4,
    comment: 'Great service and beautiful results. Only minor feedback is the wait time was a bit long.',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    customer: {
      id: 'profile-3',
      user_id: 'customer-3',
      full_name: 'Sarah Williams',
      avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
      phone: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

export const mockBookings: Booking[] = [
  {
    id: '1',
    customer_id: 'customer-1',
    salon_id: '1',
    staff_id: '1',
    service_id: '1',
    booking_date: new Date().toISOString().split('T')[0],
    start_time: '10:00',
    end_time: '11:00',
    status: 'confirmed',
    total_amount: 85,
    platform_commission: 12.75,
    vendor_payout: 72.25,
    notes: null,
    payment_method: 'online',
    payment_status: 'paid',
    paid_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    salon: mockSalons[0],
    staff: mockStaff[0],
    service: mockServices[0],
  },
  {
    id: '2',
    customer_id: 'customer-2',
    salon_id: '1',
    staff_id: '2',
    service_id: '2',
    booking_date: new Date().toISOString().split('T')[0],
    start_time: '11:30',
    end_time: '13:30',
    status: 'in_progress',
    total_amount: 180,
    platform_commission: 27,
    vendor_payout: 153,
    notes: 'First-time customer',
    payment_method: 'cash',
    payment_status: 'pending',
    paid_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    salon: mockSalons[0],
    staff: mockStaff[1],
    service: mockServices[1],
  },
  {
    id: '3',
    customer_id: 'customer-3',
    salon_id: '1',
    staff_id: '1',
    service_id: '4',
    booking_date: new Date().toISOString().split('T')[0],
    start_time: '14:00',
    end_time: '14:45',
    status: 'pending',
    total_amount: 65,
    platform_commission: 9.75,
    vendor_payout: 55.25,
    notes: null,
    payment_method: 'cash',
    payment_status: 'pending',
    paid_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    salon: mockSalons[0],
    staff: mockStaff[0],
    service: mockServices[3],
  },
];

export const generateTimeSlots = (startHour: number = 9, endHour: number = 18): string[] => {
  const slots: string[] = [];
  for (let hour = startHour; hour < endHour; hour++) {
    slots.push(`${hour.toString().padStart(2, '0')}:00`);
    slots.push(`${hour.toString().padStart(2, '0')}:30`);
  }
  return slots;
};
